CREATE TABLE likes(
like_id SERIAL PRIMARY KEY,
user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
liked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);